format = """
$hostname\
$os\
[░▒▓]()\
[▓]()\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[ ]()\
$time\
[ ]()\
\n$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✖](bold red)'
# error_symbol = '[\(╯°-°\)╯︵┻━┻](bold red)'
[os]
format = "[$symbol]($style) "
disabled = false

# This is the default symbols table.
[os.symbols]
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = " "
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[directory]
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚"
"Pictures" = " "

[git_branch]
symbol = " "
format = '[[ $symbol $branch ]()]($style)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[hostname]
ssh_only = true
ssh_symbol = ' '
format = '[[$ssh_symbol](bold)$hostname]($style) '

[nodejs]
symbol = " "
format = '[[ $symbol ($version) ]()]($style)'

[rust]
symbol = " "
format = '[[ $symbol ($version) ]()]($style)'

[golang]
symbol = " "
format = '[[ $symbol ($version) ]()]($style)'

[php]
symbol = " "
format = '[[ $symbol ($version) ]()]($style)'

[time]
disabled = false
time_format = "%I:%M:%S %p"     # Hour:Minute Format
format = '[[$time ]()]($style)'
