onboarding = false
[theme]
name = "catppuccin"
auto_switch = false

[keys]
prefix = "ctrl+a"

navigate_workspace_down = ["down", "j"]
navigate_workspace_up = ["up", "k"]

toggle_sidebar = ["prefix+b"]

next_workspace = ["prefix+tab"]
previous_workspace = ["prefix+shift+tab"]

next_agent = "prefix+a"
previous_agent = "prefix+shift+a"

focus_pane_left = ["prefix+h", "ctrl+h"]
focus_pane_down = ["prefix+j", "ctrl+j"]
focus_pane_up = ["prefix+k", "ctrl+k"]
focus_pane_right = ["prefix+l", "ctrl+l"]

[[keys.command]]
key = "prefix+u"
command = "herdr server reload-config"
description = "Reload config"

[[keys.command]]
key = ["prefix+ctrl+g", "prefix+shift+l"]
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "90%"
height = "90%"

[ui]
agent_panel_sort = "spaces"
